### ISSUE TITLE
Display or indication of "short" credential durations in timeline

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#790] opened 2019-05-06 17:01 UTC
Some credentials are active for a very short period due to corrections, e.g. "BC1071287 was created via amalgamation and then changed its name 6 minutes later.  It has an “Amalgamation” credential for “COMATT ENTERPRISES LTD.” (name not visible ☹) and a “Notice of Alteration” credential for  “RISING PHOENIX FITNESS LTD.”.  Unfortunately the first credential does not appear until you zoom way in on the timeline."

Look into UI updates to provide an indication that these short duration credentials exist.

**Comment by swcurran** [comment] 2019-09-04 16:42
Closing this - duplicate of #814.

**Closed by swcurran** 2019-09-04 16:42 UTC
Labels: duplicate
